In [1]:
import numpy as np

In [2]:
list = [[1,2,3], [5,6,7], [7,8,9]]

In [3]:
matrix = np.matrix(list)

In [4]:
matrix

matrix([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

In [5]:
matrix.sum()

48

In [6]:
matrix.max()

9

In [7]:
matrix.min()

1

In [8]:
matrix.max(axis=0)

matrix([[7, 8, 9]])

In [9]:
matrix.max(axis=1)

matrix([[3],
        [7],
        [9]])

In [10]:
matrix.sum(axis=0)

matrix([[13, 16, 19]])

In [11]:
matrix.sum(axis=1)

matrix([[ 6],
        [18],
        [24]])

In [12]:
transpose = matrix.T

In [13]:
transpose

matrix([[1, 5, 7],
        [2, 6, 8],
        [3, 7, 9]])

In [14]:
py_list = matrix.flat

In [15]:
for i in py_list:
    print(i)

1
2
3
5
6
7
7
8
9


In [16]:
matrix.ndim #dimension of an array or matrix

2

In [17]:
matrix.size

9

In [18]:
matrix.shape

(3, 3)

In [19]:
matrix.nbytes

36

# next level

In [20]:
list

[[1, 2, 3], [5, 6, 7], [7, 8, 9]]

In [21]:
matrix

matrix([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

In [22]:
matrix.nbytes

36

In [23]:
import sys
sys.getsizeof(1) * len(list)

84

In [24]:
matrix.nbytes < sys.getsizeof(1)*len(list)

True

In [25]:
oned = np.array([18,3,63,73,43,12])

# arg() functions returns index rather than values

In [26]:
oned.argmax() #returns the index of highest value

3

In [27]:
oned[oned.argmax()]

73

In [28]:
oned.argmin()

1

In [29]:
oned[oned.argmin()]

3

In [30]:
matrix.argmax()

8

In [31]:
matrix.argmin()

0

In [32]:
matrix.argmax(axis=0)

matrix([[2, 2, 2]], dtype=int64)

In [33]:
matrix.argmax(axis=1)

matrix([[2],
        [2],
        [2]], dtype=int64)

In [34]:
matrix.argmin(axis=0)

matrix([[0, 0, 0]], dtype=int64)

In [35]:
matrix.argmin(axis=1)

matrix([[0],
        [0],
        [0]], dtype=int64)

In [36]:
oned

array([18,  3, 63, 73, 43, 12])

In [37]:
oned.argsort()

array([1, 5, 0, 4, 2, 3], dtype=int64)

In [38]:
matrix

matrix([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

In [39]:
matrix.argsort()

matrix([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]], dtype=int64)

In [40]:
matrix.argsort(axis=0)

matrix([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]], dtype=int64)

In [41]:
matrix.argsort(axis=1)

matrix([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]], dtype=int64)

In [42]:
pylist1 = [2,4,6]
pylist2 = [3,6,9]
pylist1 + pylist2 #concates the list

[2, 4, 6, 3, 6, 9]

In [43]:
nparr1 = np.array(pylist1)
nparr2 = np.array(pylist2)
nparr1 + nparr2          #gives sun of values

array([ 5, 10, 15])

In [44]:
nparr1 * nparr2

array([ 6, 24, 54])

In [45]:
nparr1

array([2, 4, 6])

In [46]:
np.sqrt(nparr1)

array([1.41421356, 2.        , 2.44948974])

In [47]:
np.sqrt(matrix)

matrix([[1.        , 1.41421356, 1.73205081],
        [2.23606798, 2.44948974, 2.64575131],
        [2.64575131, 2.82842712, 3.        ]])

In [48]:
oned

array([18,  3, 63, 73, 43, 12])

In [49]:
np.sqrt(oned)

array([4.24264069, 1.73205081, 7.93725393, 8.54400375, 6.55743852,
       3.46410162])

In [50]:
np.where(oned>40)

(array([2, 3, 4], dtype=int64),)

In [51]:
matrix

matrix([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

In [52]:
np.where(matrix>6)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [53]:
np.nonzero(matrix)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [54]:
np.count_nonzero(matrix)

9

In [55]:
np.nonzero(oned)

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [56]:
oned[1]

3

In [57]:
oned[1]=0

In [58]:
np.nonzero(oned)

(array([0, 2, 3, 4, 5], dtype=int64),)